Vagrant.configure("2") do |config|
  config.vm.define "servidor" do |servidor|
    servidor.vm.box = "ubuntu/jammy64"
    servidor.vm.network "private_network", ip: "192.168.50.3"
  end

  config.vm.define "servidor2" do |servidor2|
    servidor2.vm.box = "ubuntu/jammy64"
    servidor2.vm.network "private_network", ip: "192.168.50.2"
  end
end
