# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  # Configuración de la Máquina 1: Firewall
  config.vm.define "firewall" do |fw|
    fw.vm.box = "ubuntu/bionic64"
    fw.vm.hostname = "firewall"
    fw.vm.network "private_network", ip: "192.168.90.4"
    fw.vm.provider "virtualbox" do |vb|
    end
  end

  # Configuración de la Máquina 2: DNS Maestro
  config.vm.define "dns_master" do |master|
    master.vm.box = "ubuntu/bionic64"
    master.vm.hostname = "dns-master"
    master.vm.network "private_network", ip: "192.168.90.2"
    master.vm.provider "virtualbox" do |vb|
    end
  end

  # Configuración de la Máquina 3: DNS Esclavo
  config.vm.define "dns_slave" do |slave|
    slave.vm.box = "ubuntu/bionic64"
    slave.vm.hostname = "dns-slave"
    slave.vm.network "private_network", ip: "192.168.90.3"
    slave.vm.provider "virtualbox" do |vb|
    end
  end
end
